services:
  backend:
    build: ./backend
    restart: always
    ports:
      - '3030:3030'
    depends_on:
      - db   
  webrtc:
    build: ./webrtc
    restart: always
    ports:
      - '3031:3031'
  front:
    build: ./front
    restart: always
    ports:
      - '3000:3000'
    stdin_open: true
  db:
    image: postgres:14.4
    restart: always
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'pass'
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
      - db-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:5.4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "support@wam.com"
      PGADMIN_DEFAULT_PASSWORD: "azerty"
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_LISTEN_PORT: 80
    logging:
      driver: "none"
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "db:pgsql-server"
volumes:
  db-data:
  pgadmin-data: