---

- name: Add an Apt signing key
  become: true
  ansible.builtin.apt_key:
    url: "https://www.pgadmin.org/static/packages_pgadmin_org.pub"
    state: present

- name: create pgadmin4.list file in source list
  become: true
  file: 
    path: /etc/apt/sources.list.d/pgadmin4.list
    state: touch

- name: add repo to sources.list.d
  become: true
  lineinfile:
    dest: "/etc/apt/sources.list.d/pgadmin4.list"
    line: "deb https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/bullseye pgadmin4 main"
    state: present

- name: Update apt and install pgadmin
  become: true
  apt: 
    name: [
      'pgadmin4', 
      'pgadmin4-web',
    ]
    update_cache: yes
    state: latest

