---

- name: install nginx at the latest version
  become: true
  apt: 
    name: nginx
    update_cache: yes
    state: latest
  
- name: start nginx
  become: true
  service:
      name: nginx
      state: started